version: '3.8'

services:
  redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379

chat:
  image: chat/zeljo
  ports:
    -9000:3000
  environment:
  - REDIS_Host=redis
  depends on:configs:
    -redis